language: python
matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=pep8
    - python: "2.7"
      env: TEST_SUITE=py27
    - python: "3.4"
      env: TEST_SUITE=py34
install:
  - "pip install -r requirements.txt"
  - "pip install -U -r test-requirements.txt"
after_success:
  - codecov
script: |
  tox -e $TEST_SUITE
